spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/rent-a-car
    username: cofix
    password: C0fiX
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
